---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность выбирать соперника в виде бота 
  - Пользователь должен иметь возможность выбирать соперника в виде живого игрока
  - Пользователь должен иметь возможность выбирать соперника по своему уровню навыков
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен иметь возможность устанавливать время продолжительности игры
  - Пользователь должен иметь возможность признать поражение
  - Пользователь должен иметь возможность вернуться в лобби после завершения игры
non-functional :
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
implicit :
  - Сервер сайта должен обеспечивать безопасное хранение информации клиентов
  - Форма регистрации и любые другие поля ввода информации должны обеспечивать защиту от атак типа XSS, SQL Injection
  - Обеспечить постоянную сессию с помощью соответствующих cookies 
  - Корректность отображения ошибки при некорректном запросе или отсутствии соединения с сетью
  - Наличие уведомления о том, что соперник победил
  - Наличие уведомления о том, что игрок победил
  - На сайте должна быть возможность присоединятся к игре в качестве зрителя
  - На сайте должна быть возможность просматривать завершившиеся игры
